remote_theme: pmarsceill/just-the-docs
title: daniel.ai
description: Daniel's personal site
url: "https://daniel.ai" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jemoji
